const UNHINGED_TOAST_MESSAGES = [
  'FUEL ACQUIRED. BEAST SATISFIED.',
  'MACROS LOCKED. CHAOS CALIBRATED.',
  'LOG ACCEPTED. ABSOLUTE UNIT.',
  'NUTRIENT HEIST SUCCESSFUL.',
  'GAINS PROTOCOL: EXECUTED.',
  'CALORIE INPUT CONFIRMED. STAY FERAL.',
  'MEAL RECORDED. POWER LEVEL RISING.',
  'SYSTEM UPDATE: YOU ATE LIKE A LEGEND.',
  'FOOD DATA IMPRISONED IN THE LEDGER.',
  'MISSION COMPLETE. FORK DOWN, CHAMP.',
] as const;

export const getRandomToastMessage = () => {
  const randomIndex = Math.floor(Math.random() * UNHINGED_TOAST_MESSAGES.length);
  return UNHINGED_TOAST_MESSAGES[randomIndex];
};

